spring.application.name=api-monolith
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.yaml
spring.jackson.property-naming-strategy=SNAKE_CASE
server.error.include-binding-errors=always
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.mvc.problemdetails.enabled=true
spring.jpa.hibernate.ddl-auto=validate



logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web.servlet.error=DEBUG